services:
  - type: web
    name: nutrismart-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python test.py
    envVars:
      - key: CORS_ORIGIN
        value: "https://nutrition-app-vercel-url.vercel.app" 